#!/usr/bin/env python3
"""Validate the visual and research product contract for one Skill run."""

from __future__ import annotations

import argparse
import csv
import json
import re
import struct
import zipfile
from pathlib import Path


FORBIDDEN_VISUAL_MARKERS = (
    "ai生成", "ai generated", "generated by ai", "openai", "chatgpt",
    "midjourney", "claude", "gemini", "stable diffusion",
)
FORBIDDEN_POSTER_COPY = (
    "你的 marvis 工作版 mbti", "三条铁证", "双边占比", "收敛链",
    "语义可靠度", "kl 距离", "加权贡献", "#生成我的工作版mbti",
    "#生成我的数字分身报告",
)
FORBIDDEN_HABIT_TERMS = (
    "聚类", "语义", "加权", "置信度", "指标", "样本", "活跃会话",
    "时间戳", "双边", "收敛链", "项目拓扑", "source_lineage", "mtime",
    "ctime", "kl 距离",
)
EFFORT_CUES = (
    "忙", "努力", "工作", "推进", "交作业", "按时", "交付", "认真",
    "加班", "周末", "需求", "文件", "职场", "改", "做完",
)


def fail(message: str) -> None:
    raise SystemExit(f"Product validation failed: {message}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--require-feedback", action="store_true")
    args = parser.parse_args()
    root = Path(args.output_dir).expanduser().resolve()

    required = [
        "report.png", "report.html", "report.json", "data_collection.csv",
        "evidence_table.csv", "data_manifest.json", "work_mbti_return_bundle.zip",
        "internal/evidence.json", "internal/score.json",
    ]
    if args.require_feedback:
        required.append("feedback.json")
    missing = [name for name in required if not (root / name).exists() or (root / name).stat().st_size == 0]
    if missing:
        fail("missing files: " + ", ".join(missing))

    png = (root / "report.png").read_bytes()
    if len(png) < 24 or png[:8] != b"\x89PNG\r\n\x1a\n":
        fail("report.png is not a valid PNG")
    dimensions = struct.unpack(">II", png[16:24])
    if dimensions != (1800, 2400):
        fail(f"report.png is {dimensions}, expected 1800x2400")

    html = (root / "report.html").read_text(encoding="utf-8").lower()
    found_markers = [marker for marker in FORBIDDEN_VISUAL_MARKERS if marker in html]
    if found_markers:
        fail("AI watermark/branding markers found in poster HTML: " + ", ".join(found_markers))
    if "http://" in html or "https://" in html:
        fail("poster HTML contains external resources; all assets must be bundled")
    found_copy = [marker for marker in FORBIDDEN_POSTER_COPY if marker in html]
    if found_copy:
        fail("legacy or technical poster copy found: " + ", ".join(found_copy))
    for required_copy in (
        "的工作版mbti", "三大习惯 · 你的电脑说的",
        "marvis本地知识库 · 你的文件管家", "端侧模型生成不上传",
    ):
        if required_copy not in html:
            fail(f"required poster copy is missing: {required_copy}")

    report = json.loads((root / "report.json").read_text(encoding="utf-8"))
    if not report.get("display_name"):
        fail("report display_name is missing")
    expected_title = f"{report['display_name']}的工作版mbti".lower()
    if expected_title not in html:
        fail("poster title does not use the current report display_name")
    habits = report.get("habits", [])
    if len(habits) != 3:
        fail(f"poster must contain exactly three habits, found {len(habits)}")
    if any(not re.search(r"\d", item.get("text", "")) for item in habits):
        fail("each poster habit must retain at least one exact numeric fact")
    habit_copy = " ".join(f"{item.get('title', '')} {item.get('text', '')}" for item in habits).lower()
    technical_terms = [term for term in FORBIDDEN_HABIT_TERMS if term in habit_copy]
    if technical_terms:
        fail("technical terms found in poster habits: " + ", ".join(technical_terms))
    for index, item in enumerate(habits, start=1):
        copy = f"{item.get('title', '')} {item.get('text', '')}"
        if not any(cue in copy for cue in EFFORT_CUES):
            fail(f"habit {index} does not clearly communicate work effort")
    stats = {item["label"]: item for item in report.get("stats", [])}
    peak = stats.get("你的高产时段", {})
    late = stats.get("深夜产出占比", {})
    if peak.get("value") == "样本不足" or late.get("value") == "样本不足":
        fail("poster time cards must contain an observed value, never '样本不足'")

    with (root / "data_collection.csv").open(encoding="utf-8-sig", newline="") as handle:
        collection_rows = list(csv.DictReader(handle))
    if len(collection_rows) != 1:
        fail(f"data_collection.csv must contain one user row, found {len(collection_rows)}")

    with (root / "evidence_table.csv").open(encoding="utf-8-sig", newline="") as handle:
        evidence_rows = list(csv.DictReader(handle))
    white_count = sum(row.get("group") == "W_scoring_metric" for row in evidence_rows)
    gray_count = sum(row.get("group") == "G_research_candidate" for row in evidence_rows)
    if white_count < 18 or gray_count < 19:
        fail(f"evidence table is incomplete: W={white_count}, G={gray_count}")

    manifest = json.loads((root / "data_manifest.json").read_text(encoding="utf-8"))
    expected_feedback = "collected" if args.require_feedback else "pending_user_response"
    if manifest.get("feedback_status") != expected_feedback:
        fail(f"feedback_status is {manifest.get('feedback_status')}, expected {expected_feedback}")
    bundle_path = root / "work_mbti_return_bundle.zip"
    try:
        with zipfile.ZipFile(bundle_path) as bundle:
            bundle_names = set(bundle.namelist())
    except zipfile.BadZipFile:
        fail("work_mbti_return_bundle.zip is not a valid zip file")
    research_consent = manifest.get("research_consent")
    expected_bundle = {"report.png", "data_manifest.json"}
    if research_consent == "yes":
        expected_bundle.update({"data_collection.csv", "evidence_table.csv"})
    if args.require_feedback:
        expected_bundle.add("feedback.json")
    missing_bundle = sorted(expected_bundle - bundle_names)
    if missing_bundle:
        fail("return bundle missing files: " + ", ".join(missing_bundle))
    if research_consent == "no":
        leaked_research_files = sorted({"data_collection.csv", "evidence_table.csv"} & bundle_names)
        if leaked_research_files:
            fail("no-consent return bundle contains computer research tables: " + ", ".join(leaked_research_files))
    forbidden_bundle = [name for name in bundle_names if name.startswith("internal/") or name in {"report.html", "report.json"}]
    if forbidden_bundle:
        fail("return bundle contains debug artifacts: " + ", ".join(sorted(forbidden_bundle)))

    print(json.dumps({
        "status": "complete" if args.require_feedback else "awaiting_feedback",
        "report_dimensions": list(dimensions),
        "ai_watermark_markers": [],
        "data_collection_rows": 1,
        "data_collection_columns": len(collection_rows[0]),
        "white_metric_rows": white_count,
        "gray_feature_rows": gray_count,
        "feedback_status": manifest["feedback_status"],
        "return_bundle": str(bundle_path),
        "poster_contract": "work-mbti-v2",
    }, ensure_ascii=False))


if __name__ == "__main__":
    main()
